"""add_group_channel_id_column

Revision ID: 80f2b0688e29
Revises: 903ec8172ad0
Create Date: 2026-08-19 18:11:25.659623
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '80f2b0688e29'
down_revision: str | None = '903ec8172ad0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('channel_message_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('group_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_message_id')
    op.drop_column('users', 'channel_message_id')
    # ### end Alembic commands ###
