"""fix_composite_key_order_message

Revision ID: 903ec8172ad0
Revises: e5e656edda6d
Create Date: 2026-08-18 00:04:05.024002
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '903ec8172ad0'
down_revision: str | None = 'e5e656edda6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_messages', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_messages', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_messages', type_='foreignkey')
    op.drop_column('order_messages', 'order_id')
    # ### end Alembic commands ###
