"""add_user_fullname

Revision ID: c78d4d98c973
Revises: 80f2b0688e29
Create Date: 2026-08-19 18:31:14.399630
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c78d4d98c973'
down_revision: str | None = '80f2b0688e29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
