"""add_order_message_table

Revision ID: e5e656edda6d
Revises: 20260813_0001
Create Date: 2026-08-18 00:00:12.471864
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e5e656edda6d'
down_revision: str | None = '20260813_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_messages',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_messages')
    # ### end Alembic commands ###
