"""add_referral_and_discount_system

Revision ID: feac77a43d26
Revises: c78d4d98c973
Create Date: 2026-08-29 06:12:39.558378
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'feac77a43d26'
down_revision: str | None = 'c78d4d98c973'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    discounts_table = op.create_table('discounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_percentage', sa.Boolean(), nullable=False),
    sa.Column('discrete', sa.Boolean(), nullable=False),
    sa.Column('referral_milestone', sa.Integer(), nullable=True),
    sa.Column('is_overflow', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('new_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('new_customer_id')
    )
    op.create_table('discount_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_percentage', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['discount_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_discount',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_history_id', sa.BigInteger(), nullable=True),
    sa.Column('applied_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_percentage', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['discount_history_id'], ['discount_history.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default='30000', nullable=False))
    op.add_column('users', sa.Column('referrer_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'])

    # Seed initial discount milestones
    op.bulk_insert(
        discounts_table,
        [
            {
                'title': '1 ta do\'st — 20%',
                'description': '1 ta do\'stni taklif qiling va 20% chegirmaga ega bo\'ling',
                'discount_amount': 20.00,
                'is_percentage': True,
                'discrete': False,
                'referral_milestone': 1,
                'is_overflow': False,
            },
            {
                'title': '2 ta do\'st — 50%',
                'description': '2 ta do\'stni taklif qiling va 50% chegirmaga ega bo\'ling',
                'discount_amount': 50.00,
                'is_percentage': True,
                'discrete': False,
                'referral_milestone': 2,
                'is_overflow': False,
            },
            {
                'title': '3 ta do\'st — 100%',
                'description': '3 ta do\'stni taklif qiling va 100% chegirmaga ega bo\'ling',
                'discount_amount': 100.00,
                'is_percentage': True,
                'discrete': False,
                'referral_milestone': 3,
                'is_overflow': False,
            },
            {
                'title': 'Qo\'shimcha taklif',
                'description': 'Har bir qo\'shimcha do\'st uchun 10 000 so\'m',
                'discount_amount': 10000.00,
                'is_percentage': False,
                'discrete': True,
                'referral_milestone': None,
                'is_overflow': True,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'discount')
    op.drop_table('order_discount')
    op.drop_table('discount_history')
    op.drop_table('referrals')
    op.drop_table('discounts')
    # ### end Alembic commands ###

